(use-modules (ice-9 textual-ports)
             (ice-9 rdelim)
             (ice-9 regex))

;; Part 1
(with-input-from-file "1input"
  (lambda ()
    (let loop ((line (read-line))
               (sum 0))
      (if (eof-object? line)
          (simple-format #t "Part 1: ~A~%" sum)
          (let ((first-i (string-index line char-numeric?))
                (last-i (string-rindex line char-numeric?)))
            (loop (read-line)
                  (+ (string->number (string (string-ref line first-i)
                                             (string-ref line last-i)))
                     sum)))))))

(define digit-alist
  '(("0" . 0)
    ("1" . 1)
    ("2" . 2)
    ("3" . 3)
    ("4" . 4)
    ("5" . 5)
    ("6" . 6)
    ("7" . 7)
    ("8" . 8)
    ("9" . 9)
    ("one" . 1)
    ("two" . 2)
    ("three" . 3)
    ("four" . 4)
    ("five" . 5)
    ("six" . 6)
    ("seven" . 7)
    ("eight" . 8)
    ("nine" . 9)))

(define (match->number match)
  (assoc-ref digit-alist match))

;; Part 2
(define text-digits "one|two|three|four|five|six|seven|eight|nine")
(define dig-regex (make-regexp (string-append "[0-9]|" text-digits)))
(define last-dig-regex (make-regexp (string-append "[0-9]|" (string-reverse text-digits))))

(with-input-from-file "1input"
  (lambda ()
    (let loop ((line (read-line))
               (sum 0))
      (if (eof-object? line)
          (simple-format #t "Part 2: ~A~%" sum)
          (let ((first-match (match->number (match:substring (regexp-exec dig-regex line))))
                (last-match (match->number (string-reverse (match:substring (regexp-exec last-dig-regex (string-reverse line)))))))
            ;(simple-format #t "~A~%" (+ (* 10 first-match) last-match))
            (loop (read-line)
                  (+ (* 10 first-match)
                     last-match
                     sum)))))))
