(defparameter *input* '((new-stack)
                        (deal-increment . 57)
                        (cut . -4643)
                        (deal-increment . 59)
                        (cut . 5189)
                        (new-stack)
                        (deal-increment . 24)
                        (cut . 3207)
                        (deal-increment . 63)
                        (cut . 3839)
                        (deal-increment . 53)
                        (cut . -1014)
                        (deal-increment . 21)
                        (cut . -3150)
                        (new-stack)
                        (deal-increment . 39)
                        (cut . 900)
                        (deal-increment . 6)
                        (new-stack)
                        (deal-increment . 65)
                        (cut . 6108)
                        (deal-increment . 54)
                        (cut . 6343)
                        (deal-increment . 26)
                        (new-stack)
                        (cut . 8625)
                        (deal-increment . 8)
                        (cut . -1956)
                        (new-stack)
                        (cut . 8750)
                        (deal-increment . 43)
                        (cut . -2930)
                        (deal-increment . 10)
                        (cut . -2359)
                        (deal-increment . 34)
                        (cut . 390)
                        (deal-increment . 46)
                        (cut . 5467)
                        (new-stack)
                        (cut . 61)
                        (deal-increment . 4)
                        (cut . -332)
                        (new-stack)
                        (deal-increment . 74)
                        (cut . -2568)
                        (deal-increment . 54)
                        (new-stack)
                        (deal-increment . 47)
                        (cut . -9034)
                        (deal-increment . 74)
                        (cut . 2174)
                        (new-stack)
                        (deal-increment . 63)
                        (cut . -3966)
                        (deal-increment . 16)
                        (cut . 1619)
                        (deal-increment . 43)
                        (new-stack)
                        (cut . 2779)
                        (new-stack)
                        (cut . -1441)
                        (deal-increment . 52)
                        (cut . 362)
                        (deal-increment . 25)
                        (cut . -5105)
                        (new-stack)
                        (deal-increment . 25)
                        (cut . 5744)
                        (deal-increment . 69)
                        (new-stack)
                        (cut . 6645)
                        (deal-increment . 49)
                        (cut . -9379)
                        (deal-increment . 2)
                        (cut . 2768)
                        (deal-increment . 21)
                        (cut . 6900)
                        (deal-increment . 67)
                        (cut . -4226)
                        (deal-increment . 12)
                        (cut . 2541)
                        (deal-increment . 70)
                        (cut . -9160)
                        (deal-increment . 19)
                        (new-stack)
                        (cut . -7165)
                        (deal-increment . 74)
                        (new-stack)
                        (deal-increment . 65)
                        (cut . 298)
                        (deal-increment . 24)
                        (new-stack)
                        (deal-increment . 29)
                        (cut . 7412)
                        (deal-increment . 30)
                        (cut . -3224)
                        (new-stack)
                        (cut . -7213)
                        (deal-increment . 45)
                        (cut . 8295)))

(defparameter *shuffle-times* 101741582076661)
(defparameter *deck-size* 119315717514047)

;; Taken from https://rosettacode.org/wiki/Modular_exponentiation#Common_Lisp
(defun mod-expt (a n m)
   (loop with c = 1 while (plusp n) do
        (if (oddp n)
            (setf c (mod (* a c) m)))
        (setf n (ash n -1))
        (setf a (mod (* a a) m))
      finally (return c)))

(defun mod-multiplicative-inverse (n mod)
  (mod-expt n (- mod 2) mod))

(defun solve-b ()
  (loop with increment = 1
     with offset = 0
     for (instruction . value) in *input*
     do (case instruction
          (new-stack (setf increment (* increment -1)
                           offset (+ offset increment)))
          (cut (incf offset (* value increment)))
          (deal-increment (setf increment (* increment (mod-multiplicative-inverse value
                                                                                   *deck-size*)))))
     finally (let* ((final-increment (mod-expt increment *shuffle-times* *deck-size*))
                    (final-offset (* offset
                                     (- 1 final-increment)
                                     (mod-multiplicative-inverse (- 1 increment)
                                                                 *deck-size*))))
               (return (mod (+ final-offset
                               (* 2020
                                  final-increment))
                            *deck-size*)))))
