[package]
name = "aoc-breakout"
version = "0.1.0"
authors = ["Emil Segerbäck <emil.segerback@attentec.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.32.2"